#!/bin/bash
# Home Assistant Setup Guide

echo "🏠 Home Assistant Setup Guide"
echo "=============================="
echo ""

# Get Pi IP
PI_IP=$(hostname -I | awk '{print $1}')

echo "📱 Step 1: Complete Initial Setup in Web Browser"
echo "=================================================="
echo ""
echo "Before connecting with your phone, you MUST complete the initial setup"
echo "in a web browser first."
echo ""
echo "1. Open a web browser on your computer or phone"
echo "2. Go to: http://${PI_IP}:8123"
echo "   Or: http://rasp-breatheasy.local:8123"
echo ""
echo "3. Complete the setup wizard:"
echo "   - Create your admin account"
echo "   - Set your location"
echo "   - Choose your preferences"
echo ""
echo "4. Once setup is complete, you can then connect with the mobile app"
echo ""
echo "📱 Step 2: Connect Mobile App"
echo "=============================="
echo ""
echo "After completing web setup:"
echo "1. Open Home Assistant app on your phone"
echo "2. Tap 'Add Server'"
echo "3. Enter: http://${PI_IP}:8123"
echo "   Or: http://rasp-breatheasy.local:8123"
echo "4. Login with the account you created"
echo ""
echo "🔍 Troubleshooting"
echo "=================="
echo ""
echo "If you still get errors:"
echo ""
echo "1. Check Home Assistant is running:"
echo "   docker compose ps homeassistant"
echo ""
echo "2. Check logs for errors:"
echo "   docker compose logs --tail=50 homeassistant"
echo ""
echo "3. Verify you can access from browser:"
echo "   curl http://localhost:8123"
echo ""
echo "4. Check if onboarding file exists:"
echo "   ls -la ~/breatheasy/homeassistant/.storage/onboarding"
echo ""
echo "5. If stuck, reset onboarding (WARNING: deletes your account):"
echo "   rm ~/breatheasy/homeassistant/.storage/onboarding"
echo "   docker compose restart homeassistant"
echo ""

